.travis.yml
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
services:
- docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"



python:
 - 3.6
 - 3.5
 - 3.7

before_install:
 - wget https://www4.stat.ncsu.edu/~boos/var.select/diabetes.rwrite1.txt
 - mv diabetes.rwrite1.txt diabetes.data


script:
 - python3 C:\Users\Rogerio\Documents\Big Data Diploma\CEBD 1100\Homework\Homework 7 " " -x
 - python3 C:\Users\Rogerio\Documents\Big Data Diploma\CEBD 1100\Homework\Homework 7 " " -H
 - python3 C:\Users\Rogerio\Documents\Big Data Diploma\CEBD 1100\Homework\Homework 7 " "
 - python3 C:\Users\Rogerio\Documents\Big Data Diploma\CEBD 1100\Homework\Homework 7 " " -p
 - python3 C:\Users\Rogerio\Documents\Big Data Diploma\CEBD 1100\Homework\Homework 7 " " -s bogus
 - python3 C:\Users\Rogerio\Documents\Big Data Diploma\CEBD 1100\Homework\Homework 7 " " -s tc
 - python3 C:\Users\Rogerio\Documents\Big Data Diploma\CEBD 1100\Homework\Homework 7 " " -s age